name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  # schedule:
  #   - cron: '* * * * *'
  #? minute - hour - day - month - day of week
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.1-jammy
      options: --user 1001
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
#      - name: Install Playwright Browsers
#        run: pnpm playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm playwright test --project chromium --grep '@githubAction'
      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-html-report
          path: playwright-report/
          retention-days: 30