name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  # schedule:
  #   - cron: '* * * * *'
  #? minute - hour - day - month - day of week
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: mcr.microsoft.com/playwright:v1.60.0-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.5.2

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # - name: Install Playwright Browsers
      #   run: pnpm playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm exec playwright test --project chromium-ci

      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-html-report
          path: playwright-report/
          retention-days: 30
